---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
      runs-on: ubuntu-20.64
    steps:
      - name: Login to docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose --rm sh -c "flake8" 